# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'WhatTo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WhatTo

pod "CZPicker"
pod 'IQKeyboardManagerSwift', '4.0.8'
pod 'IQDropDownTextField'
pod 'MFSideMenu'


end
